no exception first time
finally after no exception
caught exception: java.lang.RuntimeException: 
finally after exception
Done!
