class ExA extends RuntimeException {  ExA(String s) {    super(s);  }}public class throw_11_tryCF_throw_tryC {  public static void main(String[] args) {    try {      try {        if (true) throw new RuntimeException("re");        System.out.println("unreachable");      } catch(ExA e) {        System.out.println("caught: " + e.toString());      } finally {        System.out.println("finally");        if (true) throw new RuntimeException("re 2");      }      System.out.println("unreachable");    } catch (RuntimeException e) {      System.out.println("caught 2: " + e.toString());    }    System.out.println("Done!");  }}